Update tutorial-0.rst:add max python version.
beeware/beeware pull request #282
Opened 2024-01-13 17:09 UTC by NADOOITChristophBa

Add the max supported version for Python to the Version-checking section of Tutorial 0.

The max version is currently 3.11.

If someone had installed a Python version that is newer than the currently supported Python versions, before the tutorial they would expect 3.12 to work. Because of that, they will run into an error when trying to build for Android. Since now the tutorial makes sure that anyone who works through the tutorial will always have a compatible version of Python or a hint to install pyenv and use that to set the version to a supported one. This error should not occur again.

I had the conversation about this in the Briefcase issues as I thought it was a problem with Briefcase and not with the documentation.

[#1602](https://github.com/beeware/briefcase/issues/1602)

## PR Checklist:

- [ ] All new features have been tested

No, and I would not know how as there is currently no tutorial on how I would do so. As only text is changed, I would expect that this might not be needed. GitHub Actions could be interesting here.

- [X] All new features have been documented

- [X] I have read the **CONTRIBUTING.md** file

Very interesting read. Would suggest putting a link to this right at the beginning of Tutorial 0 so that people already know how to contribute to the tutorial they are currently going through.

- [X] I will abide by the code of conduct

Signed-off-by: Christoph Backhaus <christoph.backhaus@nadooit.de>

2024-01-14 02:01 UTC, freakboy3742 requested changes
As I said in [my comment on the ticket that generated this PR](https://github.com/beeware/briefcase/issues/1602#issuecomment-1890169955), just adding a note that says "don't use Python 3.12" won't be acceptable.

Firstly, Python 3.12 *does* work on every platform *except* Android. We had this support *on the day of Python 3.12's release* - something that we worked very hard to ensure.

Secondly, when the next Briefcase version is released, we *will* support Python 3.12, which means this tutorial will need to be updated again. Technically, you *could* make the tutorial work on Python 3.12 *today* - it's just more detail than we want to go into for a tutorial.

That why I specifically requested that the PR *not* take the form that you've submitted here. A specific version reference *will* need to be updated later, causing us more work. A general advisory that it's a good idea to avoid .0 and .1 releases will *always* be true - and not just for BeeWare related reasons.

2024-01-14 20:45 UTC, NADOOITChristophBa commented
Sorry, but please don't take this the wrong way; I find your writing style aggressive. I don't think you're trying to be, as from the podcast you seemed quite nice and interested in people contributing, but the "firstly... secondly..." way of talking sounds like an angry father scolding their small child for why they should not touch the stove. This does not feel good and welcoming.

So, please read this in a somewhat confused but trying to understand voice.

This was your newest answer before I created this pull request:

> We're unlikely to merge a PR that adds instructions for how to use pyenv, as that's not the purpose of the tutorial. As the tutorial already says, pyenv is one of many possible ways to install Python, and from BeeWare's perspective, it doesn't really matter which one you use.

Here you talk about what would not be accepted. You talk specifically about not adding a more precise explanation on how to use pyenv. That is why I left that out. I generally would have recommended making at least a clearer recommendation so that the new user does not need to think about what tool to use. Also, they would be properly set up to work later if they need it. Instructions on how to use and install are not needed as the link to e.g., pyenv documentation would be enough.

Especially for Tutorial 0, that is for absolute newcomers, or else you would not be talking about installing python in general, removing any confusion would be helpful. But even if it was not aimed at newcomers, it should be as clear as possible. Writing documentation from a beginner's mind perspective is far more inclusive and stops people who want to learn from quitting just because it is a bit too difficult to finish the tutorial.

I also spent more than an hour writing an answer to the post this quote is coming from before I understood that by simply limiting the range of accepted python versions, the error I encountered became unlikely.

> Adding a note about Python versions would be more likely to be merged; however, instead of referring to specific version compatibility, it would be preferable to make a general note that it's generally advisable to avoid the most recent Python version, especially if it's still at a .0 or .1 release, because it takes time for the whole of the Python ecosystem to catch up to new versions. That way we don't need to constantly update the tutorial as we add support for specific versions.

And I disagree on all aspects of this. Specific is better than generality because it is clear and easy to understand. Even giving a range of 3.8 to 3.11 is too general for me. The tutorial should, in my opinion, specify one version that passes the complete tutorial. It took me a moment to even get what you are trying to say with .0 and .1 releases. Again, a complete beginner would be confused about what you are even referring to when you use versioning like that. If someone wants to start with Python, they will go to the website and download the "newest" version as the tutorial is explaining. Again, beginners are there to learn about BeeWare and Toga; you do not want to lose them with anything complex about Python versioning besides that. I understand that it is like second nature for you, and you might feel confused about how anyone can struggle with this, but "think of the children."

I have been writing Python code for a couple of years now and I do not think I have experienced this issue before

I never had to install an old version before. Adding any level of complexity here is off-putting. I usually even skip this part of the documentation because I simply never need it. "Oh, again talking about Python installation. I already have that... skip"

There is no need to constantly update the tutorial everywhere. You only need to change it here because at this point it is written what prerequisites are absolutely guaranteed to work to do the tutorial. This tutorial is to experience firsthand what BeeWare can do using a simple app, right?

Then there is this:

> Firstly, Python 3.12 does work on every platform except Android.

Then why not define a Python version that works on all platforms. From the podcast, I heard you are an iOS user and may not care as much about Android, but having a tutorial that cannot be completed by the majority of smartphone users that might be interested to see an app on their OS of choice feels wrong. I work on Mac and have access to Xcode. So, I can see my app on the iPhone Simulator, but not everyone can because they, like more than 90% of people, do not work on Mac. So, not only could they not try out working through the tutorial on iPhone, but not on Mobile in general if they accidentally picked the wrong version of Python. Everyone could experience what I did on Android but only with the right version of Python. I do not see how recommending a version of Python that is guaranteed to let someone finish the tutorial would not be a big improvement over the current state.

> Secondly, when the next Briefcase version is released, we will support Python 3.12, which means this tutorial will need to be updated again. Technically, you could make the tutorial work on Python 3.12 today - it's just more detail than we want to go into for a tutorial.

Why does that matter? Important is that it currently does not. Documentation is like code. This version, when run, causes a bug. Great that you are working on a new version that will make that go away but currently, it simply does not work.

No, you do not need to update this. That is not the point of that part of the tutorial, right? You could leave this for a long time and only update if you really need to. So when you drop 3.8, you update it to say 3.9 - 3.11... There is no reason that the newest version needs to be mentioned here. Especially not if Python version management would be explained or strongly recommended. Just simply say that if they are using a higher version, they should use pyenv to use a lower one. As long as you do not demand 3.12+ features for BeeWare, there is no need to change this as well.

P.S. I noticed that MacOS is missing all Python version information.

> It's just more detail than we want to go into for a tutorial.

This feels arbitrary to me. Having this in there makes sure that someone is even able to do the tutorial.

To me, this is not about 3.12 but about having a tutorial that anyone can pick up and simply start without the fear of running into an error if I do not go off the given path.

> That's why I specifically requested that the PR not take the form that you've submitted here. A specific version reference will need to be updated later, causing us more work. A general advisory that it's a good idea to avoid .0 and .1 releases will always be true - and not just for BeeWare related reasons.

Yes, you did, and I disagree, and I am hoping you change your mind because I think this is the better choice.

Does my pull request remove the error that I experienced? Yes.

Will it stop other people from having it? Yes.

This is better than it is now.

Also, again... No, you do not need to update it later. As long as the versions in the tutorial are compatible with the BeeWare tutorial, there is no reason to do so. This should even reduce the number of times required to change anything about the tutorial because this version will work for anyone up to the point that BeeWare drops support for 3.11. I can change the wording to make it clear that these versions are not the generally supported versions for BeeWare but for the tutorial.

To me, clearly stating versions that are guaranteed to work, and not soon will work, is what I want from a tutorial.

This way everyone, and not only Mac/iOS Users, can experience mobile testing.

2024-01-14 22:57 UTC, freakboy3742 commented
> Sorry, but please don't take this the wrong way; I find your writing style aggressive. I don't think you're trying to be, as from the podcast you seemed quite nice and interested in people contributing, but the "firstly... secondly..." way of talking sounds like an angry father scolding their small child for why they should not touch the stove. This does not feel good and welcoming.

The firstly/secondly was an attempt to enumerate the reasons why the "simple change" you proposed wasn't acceptable. If that didn't work, then I'm sorry.

I was also a little frustrated that having gone to some length writing an explanation that (I thought) explained exactly what would be acceptable, you submitted a PR that apparently ignored all that advice, and didn't ever seem to acknowledge that I had written anything at all. Again, if my frustration came out as aggression, and/or my instructions were unclear, I apologise.

> Especially for Tutorial 0, that is for absolute newcomers, or else you would not be talking about installing python in general, removing any confusion would be helpful. But even if it was not aimed at newcomers, it should be as clear as possible. Writing documentation from a beginner's mind perspective is far more inclusive and stops people who want to learn from quitting just because it is a bit too difficult to finish the tutorial.

I'm completely agreed with the overall intention of making the content as approachable as possible for beginners. However, I disagree that "just pinning the upper version" achieves this end.

For the "absolute beginner" demographic that is likely to hit problems here, "download a different version of Python" isn't a trivial thing. Downloading a version of Python other than 3.12 from python.org requires multiple navigation clicks; and we've got plenty of historical evidence that inexperienced Windows users in particular have difficulty managing multiple Python versions (and that *is* what happens - they install Python 3.12, discover they need a different Python version, then install Python 3.11, then they end up with all sorts of weird environment configurations where they try to use the Python3.12 interpreter to manage a Python 3.11 environment, ...)

On top of that, as I indicated in my previous post, the problem you're fixing here *only* exists for Android, and will only exist there until the next release of Briefcase is published. The fact that we had Python 3.12 support for almost every platform is a point of some pride; and ensuring that support was available was, in part, driven by the fact that supporting users that download the version of Python that the Python website provides removes a major impediment to completing the BeeWare tutorial.
 
> I also spent more than an hour writing an answer to the post this quote is coming from before I understood that by simply limiting the range of accepted python versions, the error I encountered became unlikely.

```
.. admonition:: Avoid new Python major versions!

   You should avoid using a major version of Python that is recently released. If the full Python version number ends with .0 or .1 (e.g., 3.12.0 or 3.12.1), that Python version is relatively new, and the Python ecosystem as a whole may not have caught up to support the new version. As a result, it's highly likely you'll experience problems, especially on mobile platforms. To be on the safe side, it's better to use an older major version of Python (e.g., 3.11.6, rather than 3.12.0).
```

Done. It doesn't need to be complex or detailed. It just needs to not say "don't use 3.12" as an absolute. It should also be called out as a highlighted note, so it is less likely to be glossed over by the reader.

> And I disagree on all aspects of this. Specific is better than generality because it is clear and easy to understand. Even giving a range of 3.8 to 3.11 is too general for me. The tutorial should, in my opinion, specify one version that passes the complete tutorial. 

Sure. We could do that. And then we get a whole new bunch of headaches.

As I've indicated previously, "just install a different version of Python" is a non-trivial instruction for some users. I've already mentioned Windows. On Linux, it's borderline impossible - or, at least, requires a level of expertise with custom package sources that, in my experience, the vast majority of Linux users do not have.

> I have been writing Python code for a couple of years now and I do not think I have experienced this issue before

For context: I've been writing Python code for over 25 years, and I've been teaching newcomers in a tutorial capacity for almost 20 years (I joined the Django core team in 2006). Believe me when I say that I am *very much* aware that you need to write tutorials to be as simple and unambiguous as possible. 

I agree that something needs to be fixed here - you're not the first person to hit this specific issue with the Android portion of the tutorial. I disagree that a simple hard upper version pin is the fix. My disagreement here is based on the multiple years experience that I have supporting users doing the BeeWare tutorial.

As for not experiencing this problem before: Pick a random Python package that isn't in the "top 10 common downloads". Go check its packaging metadata and see if it has the Python3.12 trove classifier on PyPI. If it includes a binary module, see as Python3.12 wheel has been published. You don't have to look very far to find packages that aren't Python 3.12 ready 2 months after Python 3.12 was released. That's essentially the problem we're having here; however, the presentation is a little different because of the tooling that needs to exist to get the app running on Android. 

> I never had to install an old version before. Adding any level of complexity here is off-putting. I usually even skip this part of the documentation because I simply never need it. "Oh, again talking about Python installation. I already have that... skip"

Right - and this is my point. Your own experience is contradicting the advice you're giving. Slipping a quiet. "..-3.11" into the tutorial will be ignored by the very users that need to see it. Even slipping a hard "use Python 3.X" would likely be ignored. This needs to be called out (as I did above, as an admonition) so it isn't ignored; and needs to avoid waving people away from the version of Python that is provided as the default download on python.org when today, it works *fine* on *every* platform *except* Android, and will work fine on Android in a matter of days/weeks.

2024-05-15 18:40 UTC, freakboy3742 commented
Closing this PR on the basis that 3.12 *does* now work on Android, so the motivation for this change no longer exists.

2024-05-15 18:40 UTC, closed without merging